services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/water_delivery_db
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: bash start.sh

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=water_delivery_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: