"""change: in time

Revision ID: a25d027517f3
Revises: 9c995a815185
Create Date: 2025-04-30 11:13:53.032799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25d027517f3'
down_revision: Union[str, None] = '9c995a815185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
